# Generated by Django 5.1.6 on 2025-03-07 14:09

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('configApp', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='student',
            name='email',
            field=models.EmailField(max_length=254),
        ),
    ]
